// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Whiteboard_Backend.Models;

public partial class Bild
{
    public int BilIdPk { get; set; }

    public int BilWhiteboardIdFk { get; set; }

    public byte[] BilDatei { get; set; }

    public int BilX { get; set; }

    public int BilY { get; set; }

    public virtual Whiteboard BilWhiteboardIdFkNavigation { get; set; }
}