// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Whiteboard_Backend.Models;

public partial class Nutzer
{
    public int NutIdPk { get; set; }

    public string NutAspUserIdFk { get; set; }

    public string NutAnzeigename { get; set; }

    public virtual ICollection<Whiteboard> Whiteboard { get; set; } = new List<Whiteboard>();

    public virtual ICollection<Whiteboard> BeaWhiteboardIdFk { get; set; } = new List<Whiteboard>();
}