// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Whiteboard_Backend.Models;

public partial class Text
{
    public int TexIdPk { get; set; }

    public int TexWhiteboardIdFk { get; set; }

    public string TexText { get; set; }

    public int TexX { get; set; }

    public int TexY { get; set; }

    public virtual Whiteboard TexWhiteboardIdFkNavigation { get; set; }
}