// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Online_Whiteboard_Backend.Models;

public partial class Whiteboard
{
    public int WhiIdPk { get; set; }

    public string WhiName { get; set; }

    public int WhiBesitzerIdFk { get; set; }

    public byte[] WhiZeichnung { get; set; }

    public bool WhiIstÖffentlich { get; set; }

    public virtual ICollection<Bild> Bild { get; set; } = new List<Bild>();

    public virtual ICollection<Text> Text { get; set; } = new List<Text>();

    public virtual Nutzer WhiBesitzerIdFkNavigation { get; set; }

    public virtual ICollection<Nutzer> BeaNutzerIdFk { get; set; } = new List<Nutzer>();
}