// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Online_Whiteboard_Backend.Models;

public partial class WhiteboardContext : DbContext
{
    public WhiteboardContext(DbContextOptions<WhiteboardContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<Bild> Bild { get; set; }

    public virtual DbSet<Nutzer> Nutzer { get; set; }

    public virtual DbSet<Text> Text { get; set; }

    public virtual DbSet<Whiteboard> Whiteboard { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetUsers>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);
        });

        modelBuilder.Entity<Bild>(entity =>
        {
            entity.HasKey(e => e.BilIdPk);

            entity.Property(e => e.BilIdPk).HasColumnName("bilIdPK");
            entity.Property(e => e.BilDatei)
                .IsRequired()
                .HasColumnName("bilDatei");
            entity.Property(e => e.BilWhiteboardIdFk).HasColumnName("bilWhiteboardIdFK");
            entity.Property(e => e.BilX).HasColumnName("bilX");
            entity.Property(e => e.BilY).HasColumnName("bilY");

            entity.HasOne(d => d.BilWhiteboardIdFkNavigation).WithMany(p => p.Bild)
                .HasForeignKey(d => d.BilWhiteboardIdFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bild_Whiteboard");
        });

        modelBuilder.Entity<Nutzer>(entity =>
        {
            entity.HasKey(e => e.NutIdPk);

            entity.HasIndex(e => e.NutAspUserIdFk, "UQ_AspUserId").IsUnique();

            entity.Property(e => e.NutIdPk).HasColumnName("nutIdPK");
            entity.Property(e => e.NutAnzeigename)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("nutAnzeigename");
            entity.Property(e => e.NutAspUserIdFk)
                .IsRequired()
                .HasColumnName("nutAspUserIdFK");

            entity.HasOne(d => d.NutAspUserIdFkNavigation).WithOne(p => p.Nutzer)
                .HasForeignKey<Nutzer>(d => d.NutAspUserIdFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Nutzer_AspNetUsers");

            entity.HasMany(d => d.BeaWhiteboardIdFk).WithMany(p => p.BeaNutzerIdFk)
                .UsingEntity<Dictionary<string, object>>(
                    "Bearbeitungsberechtigung",
                    r => r.HasOne<Whiteboard>().WithMany()
                        .HasForeignKey("BeaWhiteboardIdFk")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_Bearbeitungsberechtigung_Whiteboard"),
                    l => l.HasOne<Nutzer>().WithMany()
                        .HasForeignKey("BeaNutzerIdFk")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_Bearbeitungsberechtigung_Nutzer"),
                    j =>
                    {
                        j.HasKey("BeaNutzerIdFk", "BeaWhiteboardIdFk");
                        j.IndexerProperty<int>("BeaNutzerIdFk").HasColumnName("beaNutzerIdFK");
                        j.IndexerProperty<int>("BeaWhiteboardIdFk").HasColumnName("beaWhiteboardIdFK");
                    });
        });

        modelBuilder.Entity<Text>(entity =>
        {
            entity.HasKey(e => e.TexIdPk);

            entity.Property(e => e.TexIdPk).HasColumnName("texIdPK");
            entity.Property(e => e.TexText)
                .IsRequired()
                .HasColumnName("texText");
            entity.Property(e => e.TexWhiteboardIdFk).HasColumnName("texWhiteboardIdFK");
            entity.Property(e => e.TexX).HasColumnName("texX");
            entity.Property(e => e.TexY).HasColumnName("texY");

            entity.HasOne(d => d.TexWhiteboardIdFkNavigation).WithMany(p => p.Text)
                .HasForeignKey(d => d.TexWhiteboardIdFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Text_Whiteboard");
        });

        modelBuilder.Entity<Whiteboard>(entity =>
        {
            entity.HasKey(e => e.WhiIdPk);

            entity.Property(e => e.WhiIdPk).HasColumnName("whiIdPK");
            entity.Property(e => e.WhiBesitzerIdFk).HasColumnName("whiBesitzerIdFK");
            entity.Property(e => e.WhiIstÖffentlich).HasColumnName("whiIstÖffentlich");
            entity.Property(e => e.WhiName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("whiName");
            entity.Property(e => e.WhiZeichnung)
                .IsRequired()
                .HasColumnName("whiZeichnung");

            entity.HasOne(d => d.WhiBesitzerIdFkNavigation).WithMany(p => p.Whiteboard)
                .HasForeignKey(d => d.WhiBesitzerIdFk)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Whiteboard_Nutzer");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}